version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports: 
      - "5432"
  service:
    build:
      context: ./service
      args:
        app_env: ${APP_ENV}
    command: /usr/local/bin/start
    volumes:
      - ./service:/go/src/github.com/user/cpt-chewieeee/GoDoRP/service
    ports:
      - "8080:8080"
    links:
      - db
  client:
    build:
      context: ./client
    command: /usr/local/bin/start
    volumes:
      - ./client:/usr/local/src/client
    ports: 
      - "3000:3000"
  
